<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use \Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategoriesGroupByCirclesByUser(User $user)
    {
        $qb = $this->queryCategoriesByUser($user);
        $qb->groupBy('circle');

        return $qb->getQuery()->getResult();
    }

    public function queryCategoriesByUser(User $user)
    {
        $qb = $this->createQueryBuilder('category')
            ->join('category.sector','sector')
            ->join('sector.circle', 'circle')
            ->where('circle.user = :user')
            ->setParameter('user',$user)
            ->orderBy('category.name', 'ASC');

        return $qb;
    }
}
