<?php

namespace AppBundle\Repository;

/**
 * NoteLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
