app:
    resource: '@AppBundle/Controller/'
    type: annotation
#    options:
#        sitemap: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_confirmed:
    path: /register/confirmed
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: homepage
        permanent: true

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

presta_sitemap:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"